### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-arranzizquierdo#1]
Awesome job @arranzizquierdo  !!!

Here you have some tips to improve the exercise:

- [x] The inputs are not part of a navigation, check out your HTML.
- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document
- [x] You have generated a random number and saved it on a constant, now print it!
- [x] Define the logic to make the counter work
- [ ] Extract the feedback painter to a function
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs

Let me know if you have any doubts ;)

Go for it!!

**Comment by arranzizquierdo** [comment]
Thanks @nasivuela !!
I've changed some of the things but there is one that I don't understand: Extract the feedback painter to a function

I'm not able to see the fault in the function that prints in HTML... never take the value when the numbers are equal

**Comment by nasivuela** [comment]
Well done @arranzizquierdo !!

I'm closing this, but here you have some tips, in case you want to keep improving it:
- Extract the feedback painter to a function -> you are writing many times `resultElement.innerHTML = "something";`, so you can move it to a function to reuse it.
- What about adding a reset functionality?
- Responsive
- ... Whatever you want to try!

![](https://media.giphy.com/media/3o6wrw8nj9ZjKBW1ZS/giphy.gif)
